function [] = default()
% loading tables data - titles

global field_table...
    dishNreceiver_table...
    ducts_size_table...
    annulus_insulation_table....
    pipes_insulation_table...
    insulation_table...
    HEX_table...
    plant_table... % optimization V
    field_Xb_table...
    annulus_Xb_table... 
    pipes_Xb_table...
    HTS_Xb_table...
    constraints_table...
    model_type...
    location...
    plant_type...
    system_pressure...
    file_name...
    HTS_type

    model_type = 3;
    location = 1;
    plant_type = 2;
    if HTS_type<1 | isnan(HTS_type); HTS_type = 2; end
    if system_pressure<1 | isnan(system_pressure); system_pressure = 10; end
    file_name = 'Default';

dishNreceiver_table = {...
    'Collector Area [m2]',450;...
    'RMS Slope Error [m.rad]',2.12;...
    'Base Reflectivity [%]',92.5;...
    'Max Receiver Efficiency [%]',91.8;...
    }

field_table = {...
    'Azimuth Orientation [deg]',0;...
    'Elevation Orientation [deg]',0;...
    '# Dishes in Cluster',1;...
    '# Clusters in Field',1;...
    'Field Tilt Angle [deg]',0;...
    'N-S Dish Distance [m]',39;...
    'E-W Dish Distance [m]',67;...
    'HEX Distance from Center [m]',0;...
    }

% ducts_size_table = {...
%     'Hot Duct Radius [m]',0.0762.*Pscalar(system_pressure);...
%     'Cold Duct Radius [m]',0.199.*Pscalar(system_pressure);...
%     }

annulus_insulation_table = {...
    'Hot - 1st Insulation Occupation [%]',67,'MPS (MicroTherm)',80;...
    'Hot - 2nd Insulation Occupation [%]',[],'NoN / Select Material...',[];...
    'Hot - 3rd Insulation Occupation [%]',[],'NoN / Select Material...',[];...
    'Cold - 1st Insulation Thickness [m]',0.15.*Pscalar(system_pressure),'Glass Wool',80;...
    'Cold - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold- 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    }
    
pipes_insulation_table = {...
    'Hot - 1st Insulation Thickness [m]',0.15.*Pscalar(system_pressure),'MPS (MicroTherm)',80;...
    'Hot - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Hot - 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold - 1st Insulation Thickness [m]',0.08.*Pscalar(system_pressure),'MPS (MicroTherm)',80;...
    'Cold - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold- 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    }

HEX_table = {...
    'Pinch [*C]',15,[],15;...
    'Approach [*C]',15,[],15;
    'Temperature [*C]',540,[],210;...
    'Pressure [BarA]',83,[],6;...
    }

plant_table = {...
    'Supply Water Pressure [BarA]',4;...
    'Supply Water Temperature [*C]',50;...
    'Design Air Inlet Temperature [*C]',600;...
    'Turbine Peak Efficiency [%]',40;...
    }
    

%% optimization

constraints_table = {...
    'Field Size [m2]',false,[],[];...
    'Project Cost',false,[],[];...
    'Annual Net [KWhe]',false,[],[];...
    'Installed Capacity [KWe]',false,[],[];...
    'LCOE [$/KWhe]',false,[],[];...
    'Dishes in Field [#]',false,[],[];...
    'Steam Output [Ton/Hour]',false,[],[];...
    'Consumption Load / Gross [%]',false,[],[];...
    }

field_Xb_table = {...
    'Azimuth Orientation [deg]',false,-90,90;...
    'Elevation Orientation [deg]',false,-10,10;...
    '# Dishes in Cluster',false,1,30;...
    '# Clusters in Field',false,1,30;...
    'Field Tilt Angle [deg]',false,0,45;...
    'N-S Dish Distance [m]',false,39,150;...
    'E-W Dish Distance [m]',false,67,250;...
    }

pipes_Xb_table = {...
    'Hot Duct Radius [m]',false,0.03.*Pscalar(system_pressure),0.1.*Pscalar(system_pressure);...
    'Cold Duct Radius [m]',false,0.03.*Pscalar(system_pressure),0.1.*Pscalar(system_pressure);...
    'Hot - 1st Insulation Thickness [m]',false,0.03.*Pscalar(system_pressure),1.*Pscalar(system_pressure);...
    'Hot - 2nd Insulation Thickness [m]',false,0,1.*Pscalar(system_pressure);...
    'Hot - 3rd Insulation Thickness [m]',false,0,1.*Pscalar(system_pressure);...
    'Cold - 1st Insulation Thickness [m]',false,0.03.*Pscalar(system_pressure),1.*Pscalar(system_pressure);...
    'Cold - 2nd Insulation Thickness [m]',false,0,1.*Pscalar(system_pressure);...
    'Cold- 3rd Insulation Thickness [m]',false,0,1.*Pscalar(system_pressure);...
    }

annulus_Xb_table = {...
    'Hot Duct Radius [m]',false,0.03.*Pscalar(system_pressure),0.1.*Pscalar(system_pressure);...
    'Cold Duct Radius [m]',false,0.1.*Pscalar(system_pressure),1.*Pscalar(system_pressure);...
    'Hot - 1st Insulation Occupation [%]',false,1,90;...
    'Hot - 2nd Insulation Occupation [%]',false,0,90;...
    'Hot - 3rd Insulation Occupation [%]',false,0,90;...
    'Cold - 1st Insulation Thickness [m]',false,0.03.*Pscalar(system_pressure),1.*Pscalar(system_pressure);...
    'Cold - 2nd Insulation Thickness [m]',false,0,1;...
    'Cold- 3rd Insulation Thickness [m]',false,0,1;...
    }
    
    if HTS_type>1
        insulation_table = annulus_insulation_table;
        HTS_Xb_table = annulus_Xb_table;
        ducts_size_table = {...
    'Hot Duct Radius [m]',0.0762.*Pscalar(system_pressure);...
    'Cold Duct Radius [m]',0.199.*Pscalar(system_pressure);...
    }
    else
        insulation_table = pipes_insulation_table;
        HTS_Xb_table = pipes_Xb_table;
        ducts_size_table = {...
    'Hot Duct Radius [m]',0.0762.*Pscalar(system_pressure);...
    'Cold Duct Radius [m]',0.0762.*Pscalar(system_pressure);...
    }
    end

function A = Pscalar(P)
% P is system fluid pressure [BarA]
A = (1+(P-4).*(-(1-0.83333)./6)).^1.135;


