function [] = GUI_tables()
% loading tables data - titles

global field_table...
    dishNreceiver_table...
    ducts_size_table...
    annulus_insulation_table....
    pipes_insulation_table...
    insulation_table...
    HEX_table...
    plant_table... % optimization V
    field_Xb_table...
    annulus_Xb_table... 
    pipes_Xb_table...
    HTS_Xb_table...
    constraints_table...
    model_type...
    location...
    plant_type...
    system_pressure...
    file_name...
    HTS_type

    model_type = 0;
    location = 0;
    plant_type = 0;
    system_pressure = 0;
    HTS_type = 0;
    file_name = '';
     
dishNreceiver_table = {...
    'Collector Area [m2]',[];...
    'RMS Slope Error [m.rad]',[];...
    'Base Reflectivity [%]',[];...
    'Max Receiver Efficiency [%]',[];...
    }

field_table = {...
    'Azimuth Orientation [deg]',[];...
    'Elevation Orientation [deg]',[];...
    '# Dishes in Cluster',[];...
    '# Clusters in Field',[];...
    'Field Tilt Angle [deg]',[];...
    'N-S Dish Distance [m]',[];...
    'E-W Dish Distance [m]',[];...
    'HEX Distance from Center [m]',[];...
    }

ducts_size_table = {...
    'Hot Duct Radius [m]',[];...
    'Cold Duct Radius [m]',[];...
    }

annulus_insulation_table = {...
    'Hot - 1st Insulation Occupation [%]',[],'NoN / Select Material...',[];...
    'Hot - 2nd Insulation Occupation [%]',[],'NoN / Select Material...',[];...
    'Hot - 3rd Insulation Occupation [%]',[],'NoN / Select Material...',[];...
    'Cold - 1st Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold- 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    }
    
pipes_insulation_table = {...
    'Hot - 1st Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Hot - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Hot - 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold - 1st Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold - 2nd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    'Cold- 3rd Insulation Thickness [m]',[],'NoN / Select Material...',[];...
    }

HEX_table = {...
    'Pinch [*C]',[],[],[];...
    'Approach [*C]',[],[],[];...
    'Temperature [*C]',[],[],[];...
    'Pressure [BarA]',[],[],[];...
    }

plant_table = {...
    'Supply Water Pressure [BarA]',[];...
    'Supply Water Temperature [*C]',[];...
    'Design Air Inlet Temperature [*C]',[];...
    'Turbine Peak Efficiency [%]',[];...
    }
    

%% optimization

constraints_table = {...
    'Field Size [m2]',false,[],[];...
    'Project Cost',false,[],[];...
    'Annual Net [KWhe]',false,[],[];...
    'Installed Capacity [KWe]',false,[],[];...
    'LCOE [$/KWhe]',false,[],[];...
    'Dishes in Field [#]',false,[],[];...
    'Steam Output [Ton/Hour]',false,[],[];...
    'Consumption Load / Gross [%]',false,[],[];...
    }

field_Xb_table = {...
    'Azimuth Orientation [deg]',false,[],[];...
    'Elevation Orientation [deg]',false,[],[];...
    '# Dishes in Cluster',false,[],[];...
    '# Clusters in Field',false,[],[];...
    'Field Tilt Angle [deg]',false,[],[];...
    'N-S Dish Distance [m]',false,[],[];...
    'E-W Dish Distance [m]',false,[],[];...
    }

pipes_Xb_table = {...
    'Hot Duct Radius [m]',false,[],[];...
    'Cold Duct Radius [m]',false,[],[];...
    'Hot - 1st Insulation Thickness [m]',false,[],[];...
    'Hot - 2nd Insulation Thickness [m]',false,[],[];...
    'Hot - 3rd Insulation Thickness [m]',false,[],[];...
    'Cold - 1st Insulation Thickness [m]',false,[],[];...
    'Cold - 2nd Insulation Thickness [m]',false,[],[];...
    'Cold- 3rd Insulation Thickness [m]',false,[],[];...
    }

annulus_Xb_table = {...
    'Hot Duct Radius [m]',false,[],[];...
    'Cold Duct Radius [m]',false,[],[];...
    'Hot - 1st Insulation Occupation [%]',false,[],[];...
    'Hot - 2nd Insulation Occupation [%]',false,[],[];...
    'Hot - 3rd Insulation Occupation [%]',false,[],[];...
    'Cold - 1st Insulation Thickness [m]',false,[],[];...
    'Cold - 2nd Insulation Thickness [m]',false,[],[];...
    'Cold- 3rd Insulation Thickness [m]',false,[],[];...
    }
    
    if HTS_type>1
        insulation_table = annulus_insulation_table;
        HTS_Xb_table = annulus_Xb_table;
    else
        insulation_table = pipes_insulation_table;
        HTS_Xb_table = pipes_Xb_table;
    end

